services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
  
    ports:
      - "3000:3000"
  
    env_file:
      - .env
  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
    volumes:
      - ./public/uploads:/app/public/uploads
  
    depends_on:
      - db
  
  db:
    image: mongo:latest

    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    
    command: ["mongod", "--replSet", "rs0"]

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
